// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAc_308O-mCdhSMbas4vSYhnwYJZzBOn0',
    appId: '1:909863599167:web:9bc75a6cc0ce56deb04c8a',
    messagingSenderId: '909863599167',
    projectId: 'thesis-app-5f83e',
    authDomain: 'thesis-app-5f83e.firebaseapp.com',
    storageBucket: 'thesis-app-5f83e.appspot.com',
    measurementId: 'G-T1SHK8P356',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkuw5emU44s42hS8C75MExr1MdkkyE2Kw',
    appId: '1:909863599167:android:e57c580cbc285cfbb04c8a',
    messagingSenderId: '909863599167',
    projectId: 'thesis-app-5f83e',
    storageBucket: 'thesis-app-5f83e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WpZesKuDbLbMR7NUT0-vprQwysOaxAo',
    appId: '1:909863599167:ios:42a9626de3fc37eeb04c8a',
    messagingSenderId: '909863599167',
    projectId: 'thesis-app-5f83e',
    storageBucket: 'thesis-app-5f83e.appspot.com',
    iosBundleId: 'com.example.projectManagementThesisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6WpZesKuDbLbMR7NUT0-vprQwysOaxAo',
    appId: '1:909863599167:ios:8c430796da58719eb04c8a',
    messagingSenderId: '909863599167',
    projectId: 'thesis-app-5f83e',
    storageBucket: 'thesis-app-5f83e.appspot.com',
    iosBundleId: 'com.example.projectManagementThesisApp.RunnerTests',
  );
}
